# version: "3.9"  # Make sure to specify the version

services:
  flask_app:
    container_name: flask_app
    image: joshhellstrom/flask_live_app:1.0.0
    build: ./
    command: flask run --host=0.0.0.0 --port=4000
    ports:
      - "4000:4000"
    environment:
      # Using environment variables from the .env file for the database connection
      DB_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_db:5432/${POSTGRES_DB}
      # DB_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - .:/app/commodities-tracker-backend
    depends_on:
      - postgres_db

  # web:
  #   build: .
  #   ports:
  #     - "5001:5001"
  #   volumes:
  #     - .:/app
  #   environment:
  #     FLASK_ENV: development
  #   command: flask run --host=0.0.0.0 --port=5001

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5

volumes:
  pgdata: {}
