# version: '3'
services:
  web:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
    command: flask run --host=0.0.0.0 --port=5001  # Run Flask on port 5000